apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: batch-processing
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS batch_db;
    USE batch_db;
    CREATE TABLE IF NOT EXISTS price_calculations (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        original_price DECIMAL(10,2) NOT NULL,
        vat_rate DECIMAL(5,4) NOT NULL,
        vat_amount DECIMAL(10,2) NOT NULL,
        total_price DECIMAL(10,2) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        INDEX idx_created_at (created_at),
        INDEX idx_original_price (original_price)
    );
    GRANT ALL PRIVILEGES ON batch_db.* TO 'batch_user'@'%';
    FLUSH PRIVILEGES;
