apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: batch-processing
type: Opaque
data:
  # echo -n 'rootpassword' | base64
  root-password: cm9vdHBhc3N3b3Jk
  # echo -n 'batch_user' | base64
  username: YmF0Y2hfdXNlcg==
  # echo -n 'batch_password' | base64
  password: YmF0Y2hfcGFzc3dvcmQ=
